name = "stock-analysis-app"
main = "src/worker.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[assets]
directory = "static"

[env.production]
name = "stock-analysis-app-prod"

[env.staging]
name = "stock-analysis-app-staging"

[triggers]
crons = ["0 9 * * *"]

[[d1_databases]]
binding = "stock_analysis"
database_name = "stock-analysis"
database_id = "e7c168d3-ea16-411f-a0ff-69fcffabf472"